### PR TITLE
fix(floor, ceil, round): do not divide and multiply by a floating point number

### LINKED ISSUE #1003: The negative precision `floor` returns floating point result
Hey there 👋 

Thank you for developing such a nice library!

During development I faced an unexpected result caused by the `floor` function when applied with the negative precision:

```ts
expects(floor(123456, -5)).toBe(100000)
// actual is 100000.00000000001
```

I believe the rootcause is somewhere in the [`internal/withPrecision.ts`](https://github.com/remeda/remeda/blob/main/src/internal/withPrecision.ts) file during division operation.

### PR DESCRIPTION
**Pull request by owanturist**
The changes aim to increase the accuracy of the `floor`, `cail`, and `round` functions by using only integers when dividing and multiplying, avoiding floating point numbers.

Resolves #1003 

---

Make sure that you:

- [ ] ~Typedoc added for new methods and updated for changed~
- [x] Tests added for new methods and updated for changed
- [ ] ~New methods added to `src/index.ts`~
- [ ] ~New methods added to `docs/src/content/mapping` for both Lodash and Ramda.~

---

<details><summary>We use semantic PR titles to automate the release process!</summary>

https://conventionalcommits.org

PRs should be titled following using the format: `< TYPE >(< scope >)?: description`

### Available Types:

- `feat`: new functions, and changes to a function's type that would impact users.
- `fix`: changes to the runtime behavior of an existing function, or refinements to it's type that shouldn't impact most users.
- `test`: tests-only changes (transparent to users of the function).
- `docs`: changes to the documentation of a function **or the documentation site**.
- `build`, `ci`, `chore`, and `revert`: are only relevant for the internals of the library.

For scope put the name of the function you are working on (either new or
existing).

</details>

### CODE REVIEW

File: src/internal/withPrecision.ts [hunk 1]
```diff
@@ -26,7 +26,14 @@ export function withPrecision(roundingFn: (value: number) => number) {
...
-    return roundingFn(value * multiplier) / multiplier;
+    const multiplier = RADIX ** Math.abs(precision);
+
+    if (precision > 0) {
+      return roundingFn(value * multiplier) / multiplier;
+    }
+
+    // It is tricky to divide and multiple by a floating point number.
+    // Instead, it can use integers, but first divide and then multiply.
+    return roundingFn(value / multiplier) * multiplier;
```
Comment (cjquines) [inline src/internal/withPrecision.ts:37]: **nit:** i would rather we split the multiplier in either case, so it's clearer what's happening, wdyt?

```suggestion
    if (precision > 0) {
      const multiplier = RADIX ** precision;
      return roundingFn(value * multiplier) / multiplier;
    }

    // Avoid losing precision by dividing first.
    const divisor = RADIX ** -precision;
    return roundingFn(value / divisor) * divisor;
```

File: src/ceil.test.ts [hunk 2]
```diff
@@ -12,6 +12,11 @@ describe("data-first", () => {
     expect(ceil(8123.4317, -4)).toBe(10_000);
   });
 
+  // Makes sure the issue github.com/remeda/remeda/issues/1003 doesn't happen.
+  test("does not output floating point number for negative precision", () => {
+    expect(ceil(123_456, -5)).toBe(200_000);
```
Comment (cjquines) [inline src/ceil.test.ts:17]: **nit:** i think we can just add this to the last case, and omit the comment, wdyt

**Comment by cjquines** [comment]
thanks for reporting + fixing btw!!

File: src/internal/withPrecision.ts (hunk 1 above)
Comment (owanturist) [reply src/internal/withPrecision.ts:37]: yep, makes total sense to me too!

File: src/ceil.test.ts (hunk 2 above)
Comment (owanturist) [reply src/ceil.test.ts:17]: I usually prefer to keep track of tests against bugs in a separate test case with meaningful info so it is clear why the input is verified. If you are confident that the context won't be lost and forgotten, I can merge it into the previous test case.

Comment (cjquines) [reply src/ceil.test.ts:17]: hmm fair enough, i think that's fine
