### PR TITLE
fix(toCamelCase, toSnakeCase, toKebabCase): Support iOS 16.3-

### LINKED ISSUE #928: SyntaxError: Invalid regular expression: invalid group specifier name
https://caniuse.com/js-regexp-lookbehind is not supported in 5.62% of devices as of November 2024, and it seems there is not a polyfill for this. Please consider using an alternative implemention instead of look-behinds, as by using this library, we lose support for iOS 16.3 and below.

https://github.com/remeda/remeda/blob/b14511ae8d501df7c41968e5eacb69185faf5e9e/src/internal/words.ts#L38-L54

### PR DESCRIPTION
**Pull request by ariesclark**
Closes #928.

---

Make sure that you:

- [x] Typedoc added for new methods and updated for changed
- [x] Tests added for new methods and updated for changed
- [x] New methods added to `src/index.ts`
- [x] New methods added to `docs/src/content/mapping` for both Lodash and Ramda.

---

<details><summary>We use semantic PR titles to automate the release process!</summary>

https://conventionalcommits.org

PRs should be titled following using the format: `< TYPE >(< scope >)?: description`

### Available Types:

- `feat`: new functions, and changes to a function's type that would impact users.
- `fix`: changes to the runtime behavior of an existing function, or refinements to it's type that shouldn't impact most users.
- `test`: tests-only changes (transparent to users of the function).
- `docs`: changes to the documentation of a function **or the documentation site**.
- `build`, `ci`, `chore`, and `revert`: are only relevant for the internals of the library.

For scope put the name of the function you are working on (either new or
existing).

</details>

### CODE REVIEW

File: src/internal/words.ts [hunk 1]
```diff
@@ -31,30 +31,68 @@ const WHITESPACE = [
...
+    ) {
+      const lastCharacter = word.slice(-1);
+      word = word.slice(0, -1);
+      flush();
+      word = lastCharacter;
+    }
+    // 3. Digit to non-digit or non-digit to digit (e.g., "123abc" or "abc123")
+    else if (
+      (/\d/u.test(word.at(-1)!) && /\D/u.test(character)) ||
+      (/\D/u.test(word.at(-1)!) && /\d/u.test(character))
```
Comment (eranhirsch) [inline src/internal/words.ts:79]: Can't these also just be:

```suggestion
      (/\d$/u.test(word) && /\D/u.test(character)) ||
      (/\D$/u.test(word) && /\d/u.test(character))
```

**Review by eranhirsch — CHANGES_REQUESTED** [review]
I'm not that concerned about performance, but there are a few places where it's easy to improve. In general it would probably be the most efficient if we implement this as a state machine and keep a few flags for what the previous character was, instead of looking back. If we are ditching the RegExp approach there's no point not optimizing the implementation.

File: src/internal/words.ts [hunk 2]
```diff
@@ -31,30 +31,55 @@ const WHITESPACE = [
...
+  for (const character of data) {
+    if (WORD_SEPARATORS.has(character)) {
+      // Separator encountered; flush the current word.
+      flush();
+      continue;
+    }
+
+    // Detect transitions:
+    // 1. Lowercase to uppercase (e.g., "helloWorld")
+    if (word.length > 0 && /[a-z]$/u.test(word) && /[A-Z]/u.test(character)) {
```
Comment (eranhirsch) [inline src/internal/words.ts:58]: Why do we need the word length check here?

``` suggestion
    if (/[a-z]$/u.test(word) && /[A-Z]/u.test(character)) {
```

File: src/internal/words.ts [hunk 3]
```diff
@@ -31,30 +31,55 @@ const WHITESPACE = [
...
+      flush();
+    }
+    // 2. Uppercase to lowercase following multiple uppercase letters (e.g., "HELLOWorld")
```
Comment (eranhirsch) [inline src/internal/words.ts:61]: The explanation above in the RegExp explains why the two consecutive letters are an important differentiator from the lowercase case. Can you also copy that part?

File: src/internal/words.ts [hunk 4]
```diff
@@ -31,30 +31,55 @@ const WHITESPACE = [
...
+    else if (/[A-Z][A-Z]$/u.test(word) && /[a-z]/u.test(character)) {
+      const lastCharacter = word.slice(-1);
+      word = word.slice(0, -1);
+      flush();
+      word = lastCharacter;
+    }
+    // 3. Digit to non-digit or non-digit to digit (e.g., "123abc" or "abc123")
+    else if (
+      (/\d$/u.test(word) && /\D/u.test(character)) ||
+      (/\D$/u.test(word) && /\d/u.test(character))
```
Comment (eranhirsch) [inline src/internal/words.ts:71]: \D and \d are opposing conditions so we know that if one is true the other is false. The way the code is structured right now, we will run the check twice in some cases instead of relying on that fact.

```suggestion
      /\d$/u.test(word) !== /\d/u.test(character)
```

File: src/internal/words.ts [hunk 5]
```diff
@@ -31,30 +31,55 @@ const WHITESPACE = [
...
+  const flush = (): void => {
+    if (word.length > 0) {
+      results.push(word);
+      word = "";
+    }
+  };
+
+  for (const character of data) {
+    if (WORD_SEPARATORS.has(character)) {
+      // Separator encountered; flush the current word.
```
Comment (eranhirsch) [inline src/internal/words.ts:51]: The comment above also mentions more clearly that the separator would be removed, can you mention that herew?

**Review by eranhirsch — APPROVED** [review]
Thanks for handling this.

**Review by eranhirsch — APPROVED** [review]
Thanks!
